### ISSUE TITLE
 python 3.7 support

### ISSUE THREAD

**Issue by cocoaaa** [pyviz-topics/imagen#60]
Hi, I'd like to use `imagen` library with python 3.7, but it seems like it currently supports python 2.7, 3.5 and 3.6.  `conda install -c ioam imagen` fails with the following error message: 
![image](https://user-images.githubusercontent.com/8037983/66771714-d858f580-ee6f-11e9-8171-2eaf5885ef07.png)

Is there a plan for supporting python 3.7 with `imagen`? Thank you!

**Comment by jbednar** [comment]
Imagen should already support 3.7, according to its setup.py, but it looks like we haven't provided any conda packages for it.  Seems like it should have been noarch conda packages to avoid this issue, but I'm not sure how to make that change.  In the meantime, can you try installing it using `pip`?

**Comment by cocoaaa** [comment]
Thanks you, it works with `pip`.

**Comment by ceball** [comment]
Seems like not an issue (conda packages are covered by #47).
