### ISSUE TITLE
When using GenericImage(PatternGenerator): cache_image

### ISSUE THREAD

**Issue by sf-issues** [pyviz-topics/imagen#7]
Converted from SourceForge issue 2060627, submitted by ceball
Submit Date: 2008-08-19 21:05 GMT

At least tell people about images filling memory, cache_image, etc.

**Comment by jbednar** [comment]
I believe this is referring to the cache_image parameter of FileImage, which indeed does have the potential to fill up memory. However, the parameter is False by default, and the reference manual (docstring) mentions this issue already:

> If False, discards the image and pattern_sampler after drawing the pattern each time, to make it possible to use very large databases of images without running out of memory.
